// Buyer keypair persistence for the MCP server.
// On first run, generates an Ed25519 keypair and writes
// AGORA_BUYER_PRIVKEY to mcp/.env. On subsequent runs, reuses it
// (also accepting legacy ANDROMEDA_BUYER_PRIVKEY / LUMEN_BUYER_PRIVKEY
// per ADR 0013).

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ENV_PATH = path.join(HERE, ".env");

let _cached = null;

async function loadCore() {
  // Resolve @agora/core via the workspace symlink. We import lazily
  // because the MCP server should still boot if core happens to be missing
  // (e.g. fresh clone before a build).
  return import("@agora/core");
}

export async function ensureBuyerIdentity() {
  if (_cached) return _cached;
  const core = await loadCore();
  // ADR 0013: AGORA_* first, fall back to ANDROMEDA_* then LUMEN_*.
  let priv =
    process.env.AGORA_BUYER_PRIVKEY ??
    process.env.ANDROMEDA_BUYER_PRIVKEY ??
    process.env.LUMEN_BUYER_PRIVKEY;
  if (!priv) {
    const kp = await core.generateKeypair();
    priv = kp.privkey_hex;
    const line = `\n# auto-generated by Agora MCP on first boot\nAGORA_BUYER_PRIVKEY=${priv}\n`;
    try {
      if (fs.existsSync(ENV_PATH)) fs.appendFileSync(ENV_PATH, line, "utf8");
      else fs.writeFileSync(ENV_PATH, line, "utf8");
      process.stderr.write(`[agora-mcp] generated buyer keypair; pubkey=${kp.pubkey_hex}\n`);
    } catch (e) {
      process.stderr.write(`[agora-mcp] WARNING: could not persist buyer key: ${e.message}\n`);
    }
    process.env.AGORA_BUYER_PRIVKEY = priv;
    _cached = { privkey: priv, pubkey: kp.pubkey_hex };
    return _cached;
  }
  const pubkey = await core.pubkeyFor(priv);
  _cached = { privkey: priv, pubkey };
  return _cached;
}

export function tryBuyerIdentity() { return _cached; }
