// Provider identity: Ed25519 keypair persisted in .env.local.
//
// On first boot, if AGORA_PROVIDER_PRIVKEY is unset (and no
// ANDROMEDA_PROVIDER_PRIVKEY / LUMEN_PROVIDER_PRIVKEY legacy fallback
// is found), we generate one and append it to .env.local. The pubkey
// is the provider's id. ADR 0013.

import { readFileSync, writeFileSync, existsSync, appendFileSync } from "node:fs";
import path from "node:path";
import { generateKeypair, pubkeyFor } from "@agora/core";

let cached: { privkey: string; pubkey: string } | null = null;

function envFilePath(): string {
  // provider runs with cwd = provider/, so .env.local is here.
  return path.resolve(process.cwd(), ".env.local");
}

function readPrivkeyFromEnv(): string | undefined {
  return (
    process.env.AGORA_PROVIDER_PRIVKEY ??
    process.env.ANDROMEDA_PROVIDER_PRIVKEY ??
    process.env.LUMEN_PROVIDER_PRIVKEY
  );
}

export async function ensureIdentity(): Promise<{ privkey: string; pubkey: string }> {
  if (cached) return cached;
  let privkey = readPrivkeyFromEnv();
  if (!privkey) {
    const kp = await generateKeypair();
    privkey = kp.privkey_hex;
    const fp = envFilePath();
    const line = `\n# auto-generated by Agora provider on first boot\nAGORA_PROVIDER_PRIVKEY=${privkey}\n`;
    try {
      if (existsSync(fp)) appendFileSync(fp, line, "utf8");
      else writeFileSync(fp, line, "utf8");
      process.stderr.write(`[agora] generated provider keypair; pubkey=${kp.pubkey_hex}\n`);
    } catch (e) {
      process.stderr.write(`[agora] WARNING: could not persist generated key to ${fp}: ${(e as Error).message}\n`);
    }
    process.env.AGORA_PROVIDER_PRIVKEY = privkey;
    cached = { privkey, pubkey: kp.pubkey_hex };
    return cached;
  }
  const pubkey = await pubkeyFor(privkey);
  cached = { privkey, pubkey };
  return cached;
}

/** Synchronous accessor; throws if ensureIdentity hasn't been awaited yet. */
export function identityOrThrow(): { privkey: string; pubkey: string } {
  if (!cached) throw new Error("identity not initialized; await ensureIdentity() first");
  return cached;
}

export function tryIdentity(): { privkey: string; pubkey: string } | null {
  return cached;
}
